### ISSUE TITLE
All machines won't charge past 28.928kJ

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#11]
Example pictured.

Doesn't effect the function of the machine, but cannot get them to charge any higher, even with creative power sources.

![2015-08-16_03 24 05](https://cloud.githubusercontent.com/assets/7843312/9290039/7cbd6088-43c6-11e5-8e19-ae1ad006f90a.png)

**Comment by Cypher121** [comment]
Does that bar jump from 28.928 to full sometimes? What is approximate processing time of that Grinder in ticks?

**Comment by TheQuantumGeneral** [comment]
It does sometimes jump, though the jumping is a lot more apparent with the crusher.

Takes less than a second to process something.

**Comment by Cypher121** [comment]
Are you playing on a server?

**Comment by TheQuantumGeneral** [comment]
Yes

**Comment by Cypher121** [comment]
This is visual bug, machines are actually at full charge. Otherwise they wouldn't work so fast.
