### ISSUE TITLE
crusher

### ISSUE THREAD

**Issue by yukitarou** [cout970/Magneticraft-API-and-Issues#12]
When in version 0.34 put the copper ore to the crusher will to iron rubble...

**Comment by TheQuantumGeneral** [comment]
I'm not experiencing this issue, what mod is the copper ore from?

**Comment by cout970** [comment]
Do you have installed Another One Bites the Dust?

**Comment by yukitarou** [comment]
Hmm .
The main Mod is mod is this four
MineFactoryReloaded-[1.7.10]2.8.0RC3-591
ThermalExpansion-[1.7.10]4.0.1-182
industrialcraft-2-2.2.750-experimental
gregtech_1.7.10-6.00.50

![2015-08-17_21 58 10](https://cloud.githubusercontent.com/assets/13819592/9305332/84340b6c-452b-11e5-8fa6-97348bb1fc74.png)

Copper ore and iron ore has become the same for NEI
However , in the machine of other mod it has been displayed in the correct recipe

**Comment by yukitarou** [comment]
gregtech is the cause of this problem...

**Comment by Cypher121** [comment]
Oh, look, GregTech is breaking literally every other mod! Again.

**Comment by Cypher121** [comment]
If someone can confirm that it's still valid, feel free to re-open
