### ISSUE TITLE
Inserters ignore stacksize

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#16]
I have an inserter putting eggs into a chest, and the eggs are stacking up to 64.
![2015-09-03_15 31 15](https://cloud.githubusercontent.com/assets/7843312/9651219/d7cde338-5250-11e5-9b75-4d96d7302e93.png)

**Comment by Cypher121** [comment]
OK, just a couple more days of broken stuff and this will be gone.
