### ISSUE TITLE
Inserters still play animation when trying to pull from belts to full inventory

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#17]
If I have a full chest of dirt, and the inserters are putting dirt it, they will stop working if the chest is full and they try to place 2 or more dirt in. If they try to place only one dirt in however, it will be voided, and it will continue to do this. 

Eg, conveyer belt full of single items, feeding into a full chest on the same type of items with inserter putting them in, it will just void all the items on the belt.

**Comment by Cypher121** [comment]
What do you mean by "voided"? Does it just disappear from the inserter's inventory and doesn't appear after you clear some space or does inserter get stuck and then put an item after space is cleared? Because I don't think I can reproduce that even with old version.

**Comment by TheQuantumGeneral** [comment]
it leaves the inserters inventory and doesn't reappear if I take stuff out of the chest, I can make a quick video if you want.

**Comment by Cypher121** [comment]
Yeah, that would help. Bug may be gone in new versions but I'm not sure how best to cause it to surface.

**Comment by TheQuantumGeneral** [comment]
Huh, okay. It doesn't actually seem to destroy the items, it still seems like with a stack size of 1 they where still placing the item in, but it would return to the conveyer belt. 

still seems like a bug, just far less of what I thought it was 

https://www.youtube.com/watch?v=D7eBdZv9R2I&feature=youtu.be

**Comment by Cypher121** [comment]
Who the hell thought that running the inventory logic on client side is a good idea?!
