### ISSUE TITLE
Inserter only tries to extract from first non-empty slot.

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#18]
If an inserter has an item blacklisted, it should totally ignore that item when it checks an inventory.

Take the crafter for example, currently, if you are piping stuff into it, and trying to extract out, the items getting piped in will clearly take up the first slots, however, if you blacklist that item from being extracted, it means all the things being crafted after it cannot be retrieved. 

example, I have blacklisted melon slices from being taken out, and when this situation arises when it is full, no seeds can be taken out because it can't see past the melon
![2015-09-03_18 31 48](https://cloud.githubusercontent.com/assets/7843312/9653997/ce8433c6-526a-11e5-905b-376c5ab3b5eb.png)

this works, but it is very unreliable to be able to keep it at the bottom
![2015-09-03_18 31 52](https://cloud.githubusercontent.com/assets/7843312/9654008/f3f090e6-526a-11e5-8bbc-35e49b0b3270.png)

Having two inventories in the crafter, input and output would help, but this situation can occur elsewhere too.

**Comment by Cypher121** [comment]
Wow, inserters are a mess. I'll see to that.

**Comment by Cypher121** [comment]
Wait, we don't have round-robin mode. That's another bug.
