### ISSUE TITLE
[Issue] NEI Update Screen Event Issue

### ISSUE THREAD

**Issue by accessdenied0** [cout970/Magneticraft-API-and-Issues#22]
Hey dear @cout970,

I got a problem with your latest version:
I updated your mod to the latest version and since then, every time when I try to look up any recipe in NEI my client crashes. I tracked it down to Magneticraft and I surely use the latest version of NEI (1.0.5.118/1.0.4.107), AOBD (2.8.4) and Magneticraft (0.4.5). Hope you can tell me more: http://pastebin.com/944QmxAK

I have to notice If I downgrade Magneticraft (0.3.4) one Version, it works just fine...

Thank you for any help,

access_denied

**Comment by Cypher121** [comment]
Can't reproduce, probably a compatibility bug. Did you try to find a recipe for any particular item or does it crash regardless of item? How about items without any crafting recipes? Item usages? Without texture pack? There's not enough info in crash report.

**Comment by accessdenied0** [comment]
@Cypher121,

Yeah, I'm aware of that... sadly. I was hoping you would have a clue because it was working on the last version flawlessly.
To your questions: It crashes by **any** block and item this includes creative and recipe less Items, too. Any block or Item behavior is normal, this error is seemingly restricted on NEI and the recipe function.

I do not use Optifine or a specific Texture (resource pack), just some parts of Texture replacements for JABBA, Buildcraft, Gravel, Lava and a few others. But no texture-pack in for your mod and nothing larger than 64x64.

access_denied

**Comment by MechWarrior99** [comment]
What if you take out all the mods except for Magneticraft?

**Comment by accessdenied0** [comment]
@MechWarrior99,

I tried now a few mod combinations. (Also the only the Magneticraft, NEI and CCC combination.) and all were working just fine... this is very strange... because I used some mods in my opinion who could be also the reason for this crash... (Also I noticed Magneticraft doesn't have any RF conversion =P )

But this doesn't bring me the solution any closer...

access_denied

**Comment by Cypher121** [comment]
Well, I have no idea what's wrong. As for RF conversion, it only appears if there's a mod using RF API. Did you have one of those when you noticed it was missing?

**Comment by accessdenied0** [comment]
@Cypher121, 

Sorry, I don't understand... I have a few mods which use RF TE, EnderIO, Big Reactors... nearly all of my mods... I tried to connect one of your machines to the powerbank of EnderIO. Or what do you mean exactly?

I noticed since a large while that I have a duplicated "Shaped Crafting" page in NEI I'm trying to figuring out which mod this causes... anyway...

I updated your mod and I got this crash now: http://pastebin.com/N5cg6kAA I don't sure.

**Comment by Cypher121** [comment]
RF conversion is done through RF Alternator and Kinetic Generator. If these are missing, it means RF API wasn't detected in the game. And that crash is really strange, because it's, well, counter-logical. That line doesn't modify anything at all, it can't throw ConcurrentModification.

**Comment by accessdenied0** [comment]
@Cypher121, to the main problem: I wasn't able to figure out what issue I got, yet. I'm still on it.

My idea is now, because It is restricted to NEI that a recipe could be the cause. I tried the hidden function from NEI: to look up a recipe of a placed block and it doesn't crashed... but It didn't worked either... it just opened my Inventory and nothing more. I guess I'll talk to chickenbones in the near future maybe he has an idea. In the mean time I go ahead with removing mod by mod.

access_denied

**Comment by accessdenied0** [comment]
@Cypher121,

Happy news! I was able to track down which mod was responsible for this. I used a new instance of java 8 and got a much better and more accurate crash-report: http://pastebin.com/BUBLNs7C

I already disabled this mod and it worked. I apologize for this and hope I didn't bothered you to much.

Thank you a lot for your help,

access_denied
