### ISSUE TITLE
[1.7.10][0.4.5] Hardcore Ender Expansion complains and says to report that their are defective recipes

### ISSUE THREAD

**Issue by Aedda** [cout970/Magneticraft-API-and-Issues#25]
I'm using a modified Horizons: Daybreaker pack, manually updated. I went to add Magneticraft and Hardcore Ender Expansion which was already present suddenly began stopping the loading process and said I was to report this error to you immediately.  (I have since tested in a dedicated instance containing only HEE, Magneticraft, and FMP). It has however been suggested by others this may very well be a false positive. Reporting it regardless, just in case.

Brief summery:

> java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start.

> [01:40:57] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]item.ingotIron/0(ore), [Magneticraft]item.copper_coil/0, [minecraft]item.ingotIron/0(ore), [Magneticraft]item.copper_coil/0, [Magneticraft]item.ingotCarbide/0(ore), [Magneticraft]item.copper_coil/0, [minecraft]item.ingotIron/0(ore), [Magneticraft]item.copper_coil/0, [minecraft]item.ingotIron/0(ore)}

Additional lines omitted.

Full log:
http://pastebin.com/JkpDL8kj

**Comment by Cypher121** [comment]
Check Curse in an hour, 0.4.7 will fix it.
