### ISSUE TITLE
Right Click on Conveyor with Block Or Item Causes Crash

### ISSUE THREAD

**Issue by steveowashere** [cout970/Magneticraft-API-and-Issues#27]
I am in the process of making Faithful textures for Magenticraft and during testing I noticed when I right click on a conveyor to insert an item/block the game crashes, and throws the error 

'java.lang.NoClassDefFoundError: cofh/api/item/IToolHammer' 

Maybe having COFH core installed will help? I will test. 

Full log: http://paste.ee/p/he2nz
Crash log: http://paste.ee/p/JYpp4

However the inserter works perfectly.

Mod list: 
Forge 1448
Baubles 1.0.1.10
Botania r1.7-219
Chisel2 2.5.0.43
Chromaticraft V8
CodeChickenCode 1.0.6.43
DragonAPI V8g
Forge Multipart 1.1.2.331
Magneticraft 0.5.0
NEI 1.0.4.107
Pam's HC 1.7.10i
ReactorCraft V8f
RotaryCraft V8g

Edit: Installing COFHcore fixes the problem. Tested with 3.0.3-303

**Comment by Cypher121** [comment]
Fixed, will be in the next update. For now, install CoFHCore.
