### ISSUE TITLE
MagnetiCraft - Buildcraft bucketOil issue

### ISSUE THREAD

**Issue by Dominance** [cout970/Magneticraft-API-and-Issues#28]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/116 Seems as if when picking up oil it defaults to your buckets. Which cannot be used in world or in machines/tanks of any sort.

**Comment by Cypher121** [comment]
Just tested it: oil can be placed in the world and into BC tanks. What's your setup exactly?

**Comment by Dominance** [comment]
Sorry that is correct was a error on my side how ever, The buckets are still consumed when placing it inside a buildcraft combustion engine.

**Comment by Dominance** [comment]
Just seen that thanks a lot really appreciate it!
