### ISSUE TITLE
Recipe Conflict

### ISSUE THREAD

**Issue by topher2010** [cout970/Magneticraft-API-and-Issues#29]
The recipe for the MagnetiCraft Iron Coil is the same as the Malisis Doors Iron Trap Door.  I'd like to suggest a config option for a recipe change if this happens in modpacks.

**Comment by Cypher121** [comment]
Sorry, but I'll leave that to minetweaker. That's what it's for, after all, changing recipes. I'm pretty sure that any pack that includes both Magneticraft and Malisis' mods can have minetweaker script too.
