### ISSUE TITLE
Crash when Block Breaker tries to break a whitelisted or blacklisted block

### ISSUE THREAD

**Issue by kaikue** [cout970/Magneticraft-API-and-Issues#31]
Crash report: http://pastebin.com/9UZiKS1j

I had to remove the block breaker in MCEdit to be able to open the world again.

**Comment by parcel31u** [comment]
Same with inserter trying to pick up whitelisted blocks http://pastebin.com/hHvK64aC

using version 0.5.1

**Comment by Cypher121** [comment]
Fixed that one too.

**Comment by hron84** [comment]
@Cypher121 I got same exception with inserter. Which version includes the fix?
