### ISSUE TITLE
Inserter filter option buttons not working

### ISSUE THREAD

**Issue by TheDarkPreacher** [cout970/Magneticraft-API-and-Issues#33]
Inserter caused a crash when placing something in the lefthand side of the inventory. Pastebin link to follow.

http://pastebin.com/3vux98b6

**Comment by TheDarkPreacher** [comment]
seems as though the blacklist feature of inserters causes a crash if they run across the item that is blacklisted.

**Comment by Cypher121** [comment]
Same as #31. Set it to ignore NBT.

**Comment by TheDarkPreacher** [comment]
sadly, it WAS set to ignore NBT. still crashed.

**Comment by Cypher121** [comment]
Now that's strange. Will look into it.
