### ISSUE TITLE
Rotarycraft (may be others as well) replace the inifinite water block instead of going at the side of it

### ISSUE THREAD

**Issue by b0bst3r** [cout970/Magneticraft-API-and-Issues#34]
magneticraft-0.5.1.jar
RotaryCraft 1.7.10 V9b.jar

Repeatable Steps

1 - place down Infinite Water block
2 - place down a Rotarycraft Reservoir by clicking the side of the inifinite water block

What happens is the Infinite water block completely vanishes and the reservoir takes the place of the infinite water block.

So far I've done this (because I keep forgetting) with the Rotarycraft Fermenter and Reservoir.

**Comment by Cypher121** [comment]
Apparently someone thought giving it all properties of water block was a good idea.
