### ISSUE TITLE
Inserter not pulling out of IC2 machines anymore

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#43]
This setup was working before updating to the newest version, now it won't. I tried to rotate one of them to see if it was side specific but still no luck.  

![2015-10-22_16 11 53](https://cloud.githubusercontent.com/assets/7843312/10657467/a54de70c-78d7-11e5-8b05-6f30d553d77a.png)

**Comment by Cypher121** [comment]
Does it work for other types of transportation, like BC pipes? This might be a problem with pulling directions.

**Comment by TheQuantumGeneral** [comment]
Yeah all normal methods of pulling out work, I can't even use inserters to pull out of vanilla furnaces it seems, though I can pull out of chests.

**Comment by TheQuantumGeneral** [comment]
Also, had to run the forge option of removeerrroringtileentities=true and whenever an inserter tries to pull from a crafter it disappears.

**Comment by Cypher121** [comment]
wat

**Comment by TheQuantumGeneral** [comment]
Not sure why, server just crashed when an inserter tried to pull some iron ore off a conveyer belt.

But i've had lots of conveyer belts and inserters working together no issue with this update. 

http://pastebin.com/82PVNSc3

**Comment by Cypher121** [comment]
That is a known bug with NBT filter. "Ignore NBT" mode fixes it mostly.

**Comment by Cypher121** [comment]
https://i.imgur.com/lFbhpYp.jpg about sums up how inserters work.

**Comment by Cypher121** [comment]
Or at least I hope so
