### ISSUE TITLE
Inserters using way too much bandwidth

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#45]
Had a few players reporting a lot of lag around my base, which consists of Magneticraft machines and not much else. With me and one other person in my base the server was sending at 6-7Mbps, after breaking 30 inserters it's down to about 1-2Mbps

I have not noticed the issue myself since im local to the server, but everyone else has been crippled by the lag. It is now much more responsive having removed them.

**Comment by Cypher121** [comment]
Ehh, ok, I can reduce that 3 times already, will see what else doesn't need constant synchronization.

**Comment by Cypher121** [comment]
Not really sure about this one, please test some more with newest version and reopen if problems persist.
