### ISSUE TITLE
Inserters using way to much bandwidth V2

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#47]
Using the latest update 0.6.0 beta 1

2 people on server, up speed before placing inserters 1Mbps

up speed after placing inserters...

![capture](https://cloud.githubusercontent.com/assets/7843312/10868104/e88b508e-80d6-11e5-87b1-10959aec8e14.PNG)

This is the inserters I placed to test

![2015-11-01_20 23 25](https://cloud.githubusercontent.com/assets/7843312/10868108/f43ef516-80d6-11e5-975e-2ed7773dc2a4.png)

Its absolutely crippling the server. Sadly going to have to remove Magneticraft and wait for release version.

**Comment by Cypher121** [comment]
Idle inserters generate a lot of bandwidth. I think it'll be fixed in next release, I'll try to do it in few days.
