### ISSUE TITLE
Crash report with latest build 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [cout970/Magneticraft-API-and-Issues#50]
Woke up this morning with 31 crash reports and a looping server, this mentions magneticraft so Ill try it here. 

http://pastebin.com/SGknuKnA

**Comment by Cypher121** [comment]
Strange. Can you open your magneticraft jar with some archive manager and see if class file report is talking about is there?

**Comment by TheQuantumGeneral** [comment]
yep its there

![capture](https://cloud.githubusercontent.com/assets/7843312/10984520/212bc316-846e-11e5-97b2-9cc5482f791c.PNG)

**Comment by Cypher121** [comment]
No idea honestly. Does it keep happening?

**Comment by TheQuantumGeneral** [comment]
Nope, seemed to fix itself :/

**Comment by MechWarrior99** [comment]
Sense we don't know what is going on, and it fixed it self I am closing this. if you need to you can just open a new one. Thanks for reporting this :)
