### ISSUE TITLE
6.0-beta1 Refinery Produces No Output

### ISSUE THREAD

**Issue by Ommina** [cout970/Magneticraft-API-and-Issues#51]
While I admit I've only been stumbling through the mod for less than a day, I don't believe this is me being confused.

Creative world.  Built and formed a refinery.  Attached a source of "Hot Crude" to the refinery input.  It was consumed (and continued to be consumed), but nothing appeared in any of the output tanks.

Destroyed the input tank, reformed, ensured the input tank was empty.  Downgraded to 0.5.1.  Attached same Hot Crude source.  Output liquids work.

Empty all tanks again.  Return back to 6.0.  No output.

Once more back to 0.5.1, output returns.

Same world, same structure throughout.  No changes other than renaming the .jar.

Forge Mod Loader version 7.99.16.1448

**Comment by Cypher121** [comment]
derp

**Comment by wormzjl** [comment]
Is it possible to put out a hotfix release for this?

**Comment by Cypher121** [comment]
Later today, most likely.
