### ISSUE TITLE
Magneticraft 6.0 beta NEI crasg

### ISSUE THREAD

**Issue by 1skandar** [cout970/Magneticraft-API-and-Issues#54]
http://pastebin.com/Hgb4xrKb

Tried to craft a Forge Multipart saw. When I looked up the recipe the game CTD with this error.

**Comment by Cypher121** [comment]
How do you guys make classes magically vanish at runtime? Can't reproduce,
wtf.

**Comment by 1skandar** [comment]
Hmm, possible conflict with AOBD? It adds Magneticraft compat and if your API changed enough?

**Comment by Cypher121** [comment]
No, it's not an issue with AOBD or any other mod at all. Call comes from FML, but class loading fails for some reason. I blame Forge using outdated ASM, but will try to do something about it.

**Comment by Cypher121** [comment]
Does it keep happening, by the way?

**Comment by 1skandar** [comment]
Every time I tried looking up that recipe. I eventually gave up and reverted to the previous version. Random NEI crashes are frustrating.

**Comment by Cypher121** [comment]
That's AcademyCraft's (and their LambdaLib's) fault apparently. Nothing I can do to battle their stupid ASM4 usage. I'll notify them, but currently I'd consider it Java 8 incompatible.
