### ISSUE TITLE
How Can I Upload Localization Files?

### ISSUE THREAD

**Issue by claybiockiller** [cout970/Magneticraft-API-and-Issues#55]
I'm Clayblock, a mod localizer in china. How can I upload language files?

**Comment by MechWarrior99** [comment]
Right now the best way is just to give us a download link to the files (just putting it here works) and then we will add them in. This may change later though.

**Comment by Cypher121** [comment]
don't we already have a zh_CN.lang? or is your a different dialect?

**Comment by claybiockiller** [comment]
It's not  on Github so won't release in official downloads.

**Comment by MechWarrior99** [comment]
If you give use the lang file we can add it manually.

**Comment by claybiockiller** [comment]
Localization file is here:
https://github.com/claybiockiller/Magneticraft-Chinese/blob/master/zh_CN.lang

**Comment by shobu9** [comment]
@claybiockiller ill make a new folder for the languages.
