### ISSUE TITLE
Magneticraft 6.0 beta 2 Shelving Unit minor bug and crash bug with Inventory Tweaks

### ISSUE THREAD

**Issue by 1skandar** [cout970/Magneticraft-API-and-Issues#57]
The Shelving unit will scroll its inventory using the mousewheel. However, it is also acting like a shift-mousewheel as well, as in if you hover over and item stack and mousewheel up it will transfer one of that item to your inventory AND scroll the inventory up. Mousewheel down and the inventory scrolls down and takes one of the item you are hovering over (if available).

Edit: That said, kudos on the Shelving Unit overall. I think it is one of my new favorite early game things. Keeps the chest sprawl contained and somewhat sorted.

**Comment by 1skandar** [comment]
Also I just found this. If you sort the inventory with Inventory Tweaks it will occasionally kick out a "Failed to sort container: null (l176 in HandlerSorting.java)" If you sort it again a few more times it will crash with this error: http://pastebin.com/WKdR0hTw

**Comment by Cypher121** [comment]
Yeah, that's a known bug. No idea what causes it, but I encountered it too.

**Comment by Cypher121** [comment]
Second one is something new though. I have a feeling that it's InvTweaks derping out again (it likes to do so), but I'll look into it.

**Comment by Alexismachina** [comment]
This should be fixed in 0.6.1-final in theory.
