### ISSUE TITLE
Tank GUI issue

### ISSUE THREAD

**Issue by b0bst3r** [cout970/Magneticraft-API-and-Issues#60]
The Tank in the GUI seems to be split between 3/4s tank.png and the rest from the machine/block GUI, this is highlighted when re-texturing.

http://postimg.org/image/420d9r4cp/

In the above screenshot it shows the GUI from the Polymerizer with full natural gas down the right side and bottom and I left the tank.png without a transparent background to see where the overlay is.  This makes is difficult to re-texture the GUIs.

If you look at an untextured tank in the machine GUI you can see the tank.png is 3/4s overlayed on top.

http://postimg.org/image/fsear4x55/

I've pointed to the places where the GUIs are overlaying 

http://postimg.org/image/fgwuedgp5/

The issue is tank.png is not drawing complete when there's fluid in the tanks.

**Comment by shobu9** [comment]
@b0bst3r ill look into it. But that is strange.
