### ISSUE TITLE
Crusher Jam

### ISSUE THREAD

**Issue by shobu9** [cout970/Magneticraft-API-and-Issues#61]
Sometimes the crusher jams for absoluetly no reason.

**Comment by shobu9** [comment]
It seems to only happen when the chunk unloads

**Comment by shobu9** [comment]
Ok, i will leave it like this for tonigth i have no idea why it jams, even if i set chunkloaders sometime it jams and even others said the same thing.

**Comment by Cypher121** [comment]
Machines should stop updating at all when at least a part of them is not loaded. That's why.

**Comment by shobu9** [comment]
@Cypher121 i know, but there must be a way for it to remember. Also it jams sometimes even when the chunk is CHUNKLOADED. Hense why i added the WTF tag.
