### ISSUE TITLE
Pumpjack issues

### ISSUE THREAD

**Issue by b0bst3r** [cout970/Magneticraft-API-and-Issues#62]
I think the one which causes server TPS to nosedive when it depletes all oil source blocks has been fixed so I'll leave that one out (although I did just type it in here lol)

We are seeing 2 issues on our server which need addressing but we do run cauldron so not sure if one of them is related.

1) - pickaxing pumpjacks doesn't always drop the pumpjack in the world, sometimes they just disappear.  Some of the guys on our server have mentioned they are getting them to drop if they pick the block which has the oil outlets on it.  I tried with a vanilla iron pick always on that block and have lost 7 of them now.  Not sure if this is related to Cauldron.

2) - large surface oil pools, if you get a large pool the pumpjack is not draining all the surface oil , needs to look further out.

**Comment by Cypher121** [comment]
Fixed drop problems (probably). And oil searching needs a lot of work,

**Comment by TheDarkPreacher** [comment]
Found the same issue with 0.6.0-beta2. Pumpjack does not drop at all. kinda frustrating when playing a pack like Cthulhu Awakens, where the recipe has been made more expensive.

**Comment by Krhymez** [comment]
Has this been fixed? Players from a Civilization server are reporting this pumps keeps disappearing when broken.

**Comment by MechWarrior99** [comment]
Are you all using 0.6.1-final? it should be fixed in it. if it is fixed for you please let me know so I can close this :)

**Comment by b0bst3r** [comment]
I've not had an issue with 0.6.1 final, these are all fixed
