### ISSUE TITLE
Conflict of iron stick recipe with Camping Mod

### ISSUE THREAD

**Issue by Noert** [cout970/Magneticraft-API-and-Issues#63]
Since they both use the same recipe, but essentially are unrelated items, I can only craft Camping Mod's ones on my server. Is there any fix possible for it? Maybe use of a machine for making sticks or a different recipe?

**Comment by shobu9** [comment]
@Noert You could use Minetweaker ?

**Comment by Cypher121** [comment]
That's what Minetweaker is for. Closing.
