### ISSUE TITLE
Steam Turbine Ticking Block Entity

### ISSUE THREAD

**Issue by furrious** [cout970/Magneticraft-API-and-Issues#66]
I got this error with the steam turbine, not quite sure how I managed it. I had two set up with IE pipes going to them, and as soon as I left the loaded chunk area this error came up. I went into mcedit and removed the two controllers, loaded the world back up, removed the pipes, put the turbines back together, and then as soon as i jumped through the nether portal this crash message appeared again. 

I'm just going to not use the steam turbines for now, but thought you'd at least like to look at the error report anyway. Hope it's helpful in some way.

[crash-2015-12-12_08.50.18-server.txt](https://github.com/cout970/Magneticraft-API-and-Issues/files/60048/crash-2015-12-12_08.50.18-server.txt)
[crash-2015-12-12_11.42.53-server.txt](https://github.com/cout970/Magneticraft-API-and-Issues/files/60049/crash-2015-12-12_11.42.53-server.txt)

**Comment by Alexismachina** [comment]
0.6.1-final
