### ISSUE TITLE
Crash upon RC on Infinite water block with empty bucket

### ISSUE THREAD

**Issue by TheDarkPreacher** [cout970/Magneticraft-API-and-Issues#67]
Like the title says, I had a crash when i right clicked the infinite water block with a bucket. Pastebin to follow.

http://pastebin.com/2y8uQ7Sq

**Comment by TheDarkPreacher** [comment]
followup issue. reloaded my world after the crash, and the bucket was gone.

**Comment by Cypher121** [comment]
I hate forge

**Comment by MechWarrior99** [comment]
Fixed in 0.6.1-final
