### ISSUE TITLE
Ender IO .isUsable crash

### ISSUE THREAD

**Issue by kane-thornwyrd** [cout970/Magneticraft-API-and-Issues#71]
## Env: 
* Modpack: Testbed
* Mods added for the test: 
  - Ender IO 2.3.0.422b
  - EnderCore 0.2.0.31b
  - Magneticraft 0.6.0b2.

## Crash report
https://gist.github.com/kane-thornwyrd/9e53cd170a6273cf659c

## Scenario
Shift + right click and Ender IO machine with the Magneticraft wrench.

## Theories
* Name matching signature mismatching ```isUsable``` methods
com.cout970.magneticraft.items.ItemWrench.isUsable
[crazypants.enderio.tool.TEToolProvider$TEHammer.canUse(TEToolProvider.java:29)](https://github.com/SleepyTrousers/EnderIO/blob/16b682e1cd235f3986d055919ff4f7bbba0ed20a/src/main/java/crazypants/enderio/tool/TEToolProvider.java#L29)
* Another version of the original interface/abstract may be expected.

**Comment by kane-thornwyrd** [comment]
Sorry to submit that a friday after a new year's eve... :/

**Comment by Cypher121** [comment]
Wrong API check in wrench class apparently. Method was @Optional for CoFHCore, while interface was for CoFHAPI|item. Fixed.

**Comment by kane-thornwyrd** [comment]
WAOW thank you ! dat speed !

**Comment by kane-thornwyrd** [comment]
FYI I'm a JS/PHP dev with a past experience in java 1.5, but I have no clue about MC/FML/COFH APIs ^^
