### ISSUE TITLE
Magneticraft crashes upon NEI recipe lookup with Minetweaker, sometimes

### ISSUE THREAD

**Issue by mdfntr** [cout970/Magneticraft-API-and-Issues#72]
Mods:
- Forge 10.13.4.1566
- CodeChickenLib-1.7.10-1.1.3.138-universal
- CodeChickenCore-1.7.10-1.0.7.47-universal
- ForgeMultipart-1.7.10-1.2.0.345-universal
- magneticraft-0.6.0-beta2
- MineTweaker3-1.7.10-3.0.10B
- NotEnoughItems-1.7.10-1.0.5.118-universal

Steps to reproduce:

1. Create a Minetweaker script containing an error related to removing a Magneticraft recipe, e.g. `mods.magneticraft.Crusher.removeRecipe(<minecraft:ironOre>);`
2. Launch the game and enter a new world. You should get a chat message indicating your error. (`ERROR: test.zs:1: Could not resolve <minecraft : ironOre>`)
3. Look up the recipe and/or uses for an item using NEI, and notice that it works properly.
4. Fix the error in the Minetweaker script (`<minecraft:ironOre>` -> `<minecraft:iron_ore>`) and execute `/mt reload`. You should receive a message indicating successful execution of the command (`Scripts reloaded`).
5. At this point, looking up the recipe or uses for any item in NEI crashes the game. See below for log.

Although this seems like it would primarily affect modpack authors and could be avoided/worked around, it can also affect normal players. With a particular more complicated script I have been working on, everything works fine on the first execution but a `/mt reload` results in a null pointer error in Minetweaker and triggers the bug. This also happens upon exiting and re-entering a world, where the bug would affect a normal player as well. I am working to isolate the problem in the more complicated script and will post my results here.

Minecraft log:
http://pastebin.com/pr7gC4PM

Minetweaker log:
```
INFO: MineTweaker: Building registry
INFO: MineTweaker: Sucessfully built item registry
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: test.zs:1: Could not resolve <minecraft : ironOre>
INFO: Removing null
INFO: Re-Adding null
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
INFO: Removing Crusher Recipe, Input: Iron Ore, Main Output: Iron Chunk, Primary Output: Iron Dust with 5%%, Secondary Output: Nickel Dust with 5%%
```

**Comment by MechWarrior99** [comment]
This has been fixed in 0.6.1-final.
