### ISSUE TITLE
No item output in the Pump Jack 

### ISSUE THREAD

**Issue by Tsyklop** [cout970/Magneticraft-API-and-Issues#78]
Pump Jack drop item on the ground. Item ducts are not connected to it

Magneticraft 0.6.1 final

**Comment by Nova001Sol** [comment]
Does it need to connect to itemducts? It's more of a pump than a mining device, really, so I'd say it's fine as it is.

**Comment by MechWarrior99** [comment]
I think if you put a chest next to the center block the items will go in to that if I remember right.
