### ISSUE TITLE
Remove "Concrete" after breake Pump Jack

### ISSUE THREAD

**Issue by Tsyklop** [cout970/Magneticraft-API-and-Issues#79]
"Concrete" no remove after break Pump Jack.

Magneticraft 0.6.1 final

**Comment by b0bst3r** [comment]
It's not supposed to, do you want to leave holes everywhere for people to fall down?

**Comment by Tsyklop** [comment]
@b0bst3r no!

**Comment by Alexismachina** [comment]
Can you give me more details, i don't really understand what you are asking for...

**Comment by b0bst3r** [comment]
When the pumpjack bores down to the oil blocks it leaves a concrete post in each block, when you break the pumpjack it does not break all the concrete posts which is what he's asking for and I think it's the wrong decision.  At least you can't fall to your death running over a conrete post but if it left a hole and you fell in it, you would.

**Comment by MechWarrior99** [comment]
The concrete is left on purpose so you can't fall to your death. :)
