### ISSUE TITLE
Miner dupe bug

### ISSUE THREAD

**Issue by DevTimur** [cout970/Magneticraft-API-and-Issues#99]
Tested on ver. 1.7.10

If you mine some territory with miner, and export resource to adjacent intentory, sometime it cause wierd inventory bug.
For example if you export into Strongbox "Thermal expansion",  you will start "filling" only first slot, item type of FIRST slot will change to last mined item.
https://i.gyazo.com/bdddebfdbb6e9b7012fecd04795d0667.gif
Why i call it "Dupe"? Because you can place ANY block so it get mined LAST, and you will get 64 of this block type. You can also use block with internal inventory (Strongbox "Therm Exp", Vacum chest "EnderIO", etc.) and get 64 strongboxes full of items inside.
https://i.gyazo.com/e0671220feb2a8bf2d484ee439357186.gif

**Comment by MechWarrior99** [comment]
Thank you very much for taking the time to report this and for putting so much effort in to it. However we no longer support the 1.7.10 version of Magneticraft. Again, thank you though :)
